### ISSUE TITLE
Position of figure source code/data

### ISSUE THREAD

**Issue by Melissa37** [elifesciences/XML-mapping#22]
I think this was a HighWire requirement:

source code and source data for a figure was contained within the caption of that figure, but the figure supplement is not.
I have been playing with this and it is not necessary and it does not fit logically, to me.

My preference is:
`<fig id="fig4" position="float">
                        <object-id pub-id-type="doi">10.7554/eLife.13222.010</object-id>
                        <label>Figure 4.</label>
                        <caption>
                            <title>Single figure with source code.</title>
                        </caption>
                        <graphic xlink:href="elife-00666-fig4-v1"/>
                        <p>
                            <supplementary-material id="SD2-data">
                                <object-id pub-id-type="doi">10.7554/eLife.00666.011</object-id>
                                <label>Figure 4—Source code 1.</label>
                                <caption>
                                    <title>Title of the source code.</title>
                                    <p>Legend of the source code.</p>
                                </caption>
                                <media mimetype="xlsx" xlink:href="elife-00666-fig4-data1-v1.xlsx"/>
                            </supplementary-material>
                        </p>
                    </fig>`

But our current model is:
`<fig id="fig3s1" position="float" specific-use="child-fig">
                            <object-id pub-id-type="doi">10.7554/eLife.00666.008</object-id>
                            <label>Figure 3—figure supplement 1.</label>
                            <caption>
                                <title>Title of the figure supplement</title>
                                <p>
                                    <supplementary-material id="SD1-data">
                                        <object-id pub-id-type="doi">10.7554/eLife.00666.009</object-id>
                                        <label>Figure 3—figure supplement 1—Source data 1.</label>
                                        <caption>
                                            <title>Title of the figure supplement source data.</title>
                                            <p>Legend of the figure supplement source data.</p>
                                        </caption>
                                        <media mimetype="xlsx" xlink:href="elife-00666-fig3-figsupp1-data1-v1.xlsx"/>
                                    </supplementary-material>
                                </p>
                            </caption>
                            <graphic xlink:href="elife-00666-fig3-figsupp1-v1"/>
                        </fig>`

Do you agree with me to change this?

**Comment by gnott** [comment]
It looks ok when I reviewed the changes in detail - basically you've just moved the `</caption><graphic xlink:href="elife-00666-fig4-v1"/>` tag up, yes? Makes sense to me too.

To be sure, I changed the old "elife-kitchen-sink.xml" file that is used in the parseJATS parser in elifetools for one of the fig to look like this change. The current parser tests we have still pass with no issues.

**Comment by gnott** [comment]
An update to that - when it comes to figure captions, the parser is right now generally only using the contents of the first `<p>` tag inside the `<caption>` tag, and would explain why moving it had no adverse effect. That is what would get sent out to CrossRef or PubMed.

As the parser is developed further, I think it will need to do more extensive parsing of the entire caption. We should also build in the ability to handle both the old and new formats you have above in order to parse all the articles of the past and future.

**Comment by Melissa37** [comment]
OK, sounds good. Thanks
