### ISSUE TITLE
Adding PMIDs to References

### ISSUE THREAD

**Issue by Melissa37** [elifesciences/XML-mapping#3]
Does it need a url link as well as the PMID?

**Comment by Melissa37** [comment]
We will add the PMIDs.

The url is constructed http://www.ncbi.nlm.nih.gov/pubmed/"PMID value"
So, can we just add the PMID and you create the link on the website?

**Comment by thewilkybarkid** [comment]
@Melissa37 Yep! (We'll handle DOIs in the same way.)
