### ISSUE TITLE
Equal contributions

### ISSUE THREAD

**Issue by Melissa37** [elifesciences/XML-mapping#32]
HTML: not seen in rollover samples.
In author info at end of article:
Contributed equally with: Verena Schuenemann

PDF: footnote symbol and "These authors contributed equally to this work"
If 2 seperate groups, second group as footnote symbol and "These authors also contributed equally to this work"

XML currently:

``` xml
<fn fn-type="con" id="equal-contrib">
                    <label>&#x2020;</label>
                    <p>These authors contributed equally to this work</p>
                </fn>
                <fn fn-type="con" id="equal-contrib2">
                    <label>&#x2021;</label>
                    <p>These authors also contributed equally to this work</p>
                </fn>
```

**Comment by Melissa37** [comment]
Questions:
How is website currently generating equal contribution connection between authors?
We don't think we can lose the footnote from the XML due to DTD constraints but the tagging seems overcomplicated/PDF focused, so can we discuss how we could streamline it?

**Comment by thewilkybarkid** [comment]
The current website looks to be grouping them together using the ID. Does the text have any value (ie can it ever be different)? If not, they we can keep it as is for the PDF, but the JSON will ignore the footnote completely (so similar to what happens now, but the text that appears on the article info tab will be completely generated).

**Comment by Melissa37** [comment]
That works for us, the ID is what will be used in the PDF to generate the footnote.
