### ISSUE TITLE
<chem-struct-wrap>

### ISSUE THREAD

**Issue by gnott** [elifesciences/XML-mapping#46]
Does the new kitchen sink need `<chem-struct-wrap>` tag examples?

**Comment by Melissa37** [comment]
I've searched our archive using Xpath (:-)) and cannot find an instance of when we've used it, so I suggest no. We can add it in later if we need to, but I think we were planning to embed chemical structures at the outset but never did.

**Comment by gnott** [comment]
Thanks, I just noticed it in the old kitchen sink. I will ignore it!
