### ISSUE TITLE
Update to periodical reference

### ISSUE THREAD

**Issue by Melissa37** [elifesciences/XML-mapping#53]
https://github.com/elifesciences/XML-mapping/commit/504893c6246254e3bdf2c8e870d30011ce162dde

See that commit, now the date will be used and sub divisions of the date split out into day/month/year rather than mashing all into year.

**Comment by Melissa37** [comment]
From Mulberry:

I think this approach will cause you some problems both with retrieval and with display. The retrieval problems will happen because you will have the ISO date attribute in a different place than you do on all the other citations, and the display problem because you don’t have the month, day, and year either contained or in the sequence in which you want to see them (according to the requirements spreadsheet). Also, the <date> element requires content, so your sample is invalid.

May I suggest an alternative approach? I suggest:
1. Putting the @iso-8601-date on <year>, like you do in other citations,
2. putting the date as you want to see it displayed in a <string-date>, which would mean that
   the elements of the date are contained in a wrapper (and in a <string-date> not a <date> so that
   you can have the punctuation and space in the XML document)

So, your sample would be:

   `<ref id="bib40">
    <element-citation publication-type="periodical">
     <person-group person-group-type="author">
      <name>
       <surname>Schwartz</surname>
       <given-names>J</given-names>
      </name>
     </person-group>
     <string-date>September 9, <year iso-8601-date="1993-09-30">1993</year></string-date>
     <article-title>Obesity affects economic, social status</article-title>
     <source>The Washington Post</source>
     <fpage>A1</fpage>
     <lpage>A4</lpage>
    </element-citation>
   </ref>`

or, if you really think there is value in tagging the day and month (which I sort of doubt), you could do:

   `<ref id="bib40">
    <element-citation publication-type="periodical">
     <person-group person-group-type="author">
      <name>
       <surname>Schwartz</surname>
       <given-names>J</given-names>
      </name>
     </person-group>
     <string-date><month>September</month> <day>9</day>, <year iso-8601-date="1993-09-30">1993</year></string-date>
     <article-title>Obesity affects economic, social status</article-title>
     <source>The Washington Post</source>
     <fpage>A1</fpage>
     <lpage>A4</lpage>
    </element-citation>
   </ref>`

Does that make sense?

@gnott  can we discuss on the call?

**Comment by gnott** [comment]
The parser should be adaptable to where the iso date is located. I'm not sure we use it much, although it may get integrated into future work.

**Comment by Melissa37** [comment]
This is what Exeter went for:

https://github.com/elifesciences/XML-mapping/commit/4f0d4d8e01943674a967c978a414e01d4891b5f6

<ref id="bib40">
    <element-citation publication-type="periodical">
     <person-group person-group-type="author">
      <name>
       <surname>Schwartz</surname>
       <given-names>J</given-names>
      </name>
     </person-group>
     <string-date><month>September</month> <day>9</day>, <year iso-8601-date="1993-09-30">1993</year></string-date>
     <article-title>Obesity affects economic, social status</article-title>
     <source>The Washington Post</source>
     <fpage>A1</fpage>
     <lpage>A4</lpage>
    </element-citation>
   </ref>

Thanks
