### ISSUE TITLE
Timing of changes to Elife XML

### ISSUE THREAD

**Issue by adam-rehin** [elifesciences/XML-mapping#57]
Hi

Jisc PubRouter consumes Elife XML and we will need to make some changes to accommodate the Elife changes.

Can you let us know the planned release date of these changes.

thanks

Adam

**Comment by Melissa37** [comment]
Hi Adam

Thanks for reviewing these changes. We do not have a defined date, but we are currently looking at December. When I know more I'll let you know.

Thanks

M
