### ISSUE TITLE
mathml and tags in abstract in 00666

### ISSUE THREAD

**Issue by gnott** [elifesciences/XML-mapping#58]
I'm reviewing the parsing support for the abstract, including going back to before these kitchen sinks.

1. In the abstract mathml in 00666, could we / would we wrap these in an ``<inline-formula>`` tag?

2. There is also some use of the ``<sc>`` tag in abstracts in the old XML - is that no longer supported going forward?

**Comment by Melissa37** [comment]
Hey G, <sc>needs to be supported in the abstract, I've add to the kitchen sink https://github.com/elifesciences/XML-mapping/commit/b918979043f36d8632c7e2d5802b670bdd51138a#diff-565f19e8c101ba4e11b88925ebc3efdb

And math ml is contained within inline-formula now:
990d823c1615bb60cc78d5ca228da291c2b4bec2

**Comment by gnott** [comment]
Looks great thanks @Melissa37
