### ISSUE TITLE
Ethics footnotes and paragraphs

### ISSUE THREAD

**Issue by gnott** [elifesciences/XML-mapping#59]
In elife-00666.xml, I notice the "Human subjects" and "Animal subjects" content is all in the same paragraph ``<p>`` tag and in the same ``<fn>`` tag. 

Typically two ethics statements are in their own separate ``<fn>`` tag.

Could you please confirm if that is intentional @Melissa37 ?

If these are each in their own ``<fn>`` and ``<p>`` tags then might be easier for rendering the display later, and it would also match the previous XML guidelines.

**Comment by Melissa37** [comment]
Done, sorry about that!
4068de8354ab6e5377dd7394dd5eb0b4c565d2b9
