### ISSUE TITLE
Funding award-group principal-award-recipient as an institution

### ISSUE THREAD

**Issue by gnott** [elifesciences/XML-mapping#60]
I've found some examples where a ``<principal-award-recipient>`` of a funding award is an institution, e.g. in 07383

```
<award-group id="par-1">
<funding-source>
<institution-wrap>
<institution>Laura and John Arnold Foundation</institution>
</institution-wrap>
</funding-source>
<principal-award-recipient>
<institution>Reproducibility Project: Cancer Biology</institution>
</principal-award-recipient>
</award-group>
```

Could we please have one of these type in the new kitchen sink so it is explicit? I am expecting it will not be a ``<collab>`` tag, and it would be great to have it documented in the kitchen sink.

**Comment by Melissa37** [comment]
Done, see commit: 0abc542398500a242bf509c30b48f429cc7d5fb4

**Comment by Melissa37** [comment]
Hi Pari

Please can you close this issue once you have registered this change in the Kriya system?

Thanks
M
