### ISSUE TITLE
award-group institution-id

### ISSUE THREAD

**Issue by gnott** [elifesciences/XML-mapping#61]
Could you please review this potential change to the institution-id uri (adding http://)

``
<institution-wrap><institution-id institution-id-type="FundRef">dx.doi.org/10.13039/100000011</institution-id>
``

to

``
<institution-wrap><institution-id institution-id-type="FundRef">http://dx.doi.org/10.13039/100000011</institution-id>
``

**Comment by Melissa37** [comment]
Sure, for consistency we should do this, but before I do, should it be https?

M

**Comment by gnott** [comment]
https is good I believe. You could also go "https://doi.org/10.13039/100000011"

**Comment by Melissa37** [comment]
Done! sorry for the delay:

https://github.com/elifesciences/XML-mapping/commit/3842fe2953fcf591ed3959d93c15513beda91fa8

**Comment by Melissa37** [comment]
Hi Sowmya and Pari

Can you update your scripts and close this once done?
