### ISSUE TITLE
Patent reference ext-link as uri instead of url

### ISSUE THREAD

**Issue by gnott** [elifesciences/XML-mapping#62]
bib32 in 00666 XML, it looks like the ext-link-type is url (URL),

```
<ext-link ext-link-type="url" ...
```

instead of normally this is uri (URI),

```
<ext-link ext-link-type="uri" ...
```

Should this / could this be uri instead of url?

**Comment by Melissa37** [comment]
Done, sorry about that.
See https://github.com/elifesciences/XML-mapping/commit/e320782a23e1d64ab419b077a80769eae82700ae

**Comment by Melissa37** [comment]
HI Pari and Sowmya, please close this issue once you've seen and registered the change.

Thanks

M

**Comment by SowmyaMahadevan** [comment]
Hi Melissa,

I will review with the developer and make this change and close this issue once done. 
Thanks,
Sowmya
