### ISSUE TITLE
add Editor's note to abstracts

### ISSUE THREAD

**Issue by Melissa37** [elifesciences/XML-mapping#79]

**Comment by Melissa37** [comment]
@gnott @JGilbert-eLife decided not to add this as it is relevant for so few articles and is an experiment anyway.
Is that OK with you guys?

**Comment by JGilbert-eLife** [comment]
Sounds good to me - I guess if it becomes a long-term thing, we can do a variant.

**Comment by gnott** [comment]
I think it relates to the issues thread https://github.com/elifesciences/issues/issues/2196  The changes to support it were basically completed, with no adverse impacts if you do not continue with the JATS updates.
